#!/usr/bin/env bash
set -euo pipefail
db="${ZAKI_LOCAL_DB_CONTAINER:-supabase_db_Zaki-ledger}"
q() { docker exec "$db" psql -X -v ON_ERROR_STOP=1 -U supabase_admin -d postgres -Atc "$1"; }
u=21000000-0000-0000-0000-000000000001; p=21000000-0000-0000-0000-000000000002; c=21000000-0000-0000-0000-000000000003; b=21000000-0000-0000-0000-000000000004
cleanup() { q "BEGIN; ALTER TABLE public.document_evidence_confirmations DISABLE TRIGGER document_evidence_confirmations_append_only; DELETE FROM public.document_evidence_confirmations WHERE client_entity_id='$c'; ALTER TABLE public.document_evidence_confirmations ENABLE TRIGGER document_evidence_confirmations_append_only; ALTER TABLE public.document_evidence_extractions DISABLE TRIGGER document_evidence_extractions_append_only; DELETE FROM public.document_evidence_extractions WHERE client_entity_id='$c'; ALTER TABLE public.document_evidence_extractions ENABLE TRIGGER document_evidence_extractions_append_only; ALTER TABLE public.financial_documents DISABLE TRIGGER financial_documents_require_current_revision; UPDATE public.financial_documents SET current_revision_id=NULL WHERE client_entity_id='$c'; ALTER TABLE public.financial_document_revisions DISABLE TRIGGER financial_document_revisions_immutable; DELETE FROM public.financial_document_revisions WHERE client_entity_id='$c'; ALTER TABLE public.financial_document_revisions ENABLE TRIGGER financial_document_revisions_immutable; DELETE FROM public.financial_documents WHERE client_entity_id='$c'; ALTER TABLE public.financial_documents ENABLE TRIGGER financial_documents_require_current_revision; DELETE FROM public.import_artifacts WHERE client_entity_id='$c'; ALTER TABLE public.canonical_audit_ledger DISABLE TRIGGER canonical_audit_ledger_immutable; DELETE FROM public.canonical_audit_ledger WHERE client_entity_id='$c'; ALTER TABLE public.canonical_audit_ledger ENABLE TRIGGER canonical_audit_ledger_immutable; DELETE FROM public.ledger_books WHERE id='$b'; DELETE FROM public.client_entities WHERE id='$c'; DELETE FROM public.practice_memberships WHERE practice_id='$p'; DELETE FROM public.practices WHERE id='$p'; DELETE FROM auth.users WHERE id='$u'; COMMIT;" >/dev/null; }
trap cleanup EXIT; cleanup
q "INSERT INTO auth.users(id,email,role,aud,created_at,updated_at) VALUES('$u','evidence-race@test','authenticated','authenticated',now(),now()); INSERT INTO public.practices(id,name,created_by_user_id) VALUES('$p','Evidence race','$u'); INSERT INTO public.practice_memberships(id,practice_id,user_id,role) VALUES(gen_random_uuid(),'$p','$u','owner'); INSERT INTO public.client_entities(id,practice_id,legal_name,display_name,base_currency) VALUES('$c','$p','Evidence Ltd','Evidence','USD'); INSERT INTO public.ledger_books(id,client_entity_id,book_kind,display_name,functional_currency) VALUES('$b','$c','internal','Evidence','USD');"
ingest="SELECT public.ingest_document_evidence_v1('$p','$c','$b','$u',repeat('a',64),10,'$c/a','a.pdf','application/pdf',repeat('b',64),'{}','test','1');"
e="$(q "$ingest" | sed -E 's/.*"extraction_id" *: *"([^"]+)".*/\1/')"
call="SELECT public.confirm_document_evidence_v1('$p','$c','$b','$u','$e','same',repeat('c',64),'invoice',jsonb_build_object('issuer_name','Vendor','document_number','INV-1','amount_minor','1000','currency_code','USD','minor_unit_exponent','2'));"
tmp="$(mktemp -d)"; docker exec "$db" psql -X -v ON_ERROR_STOP=1 -U supabase_admin -d postgres -Atc "$call" >"$tmp/1" & docker exec "$db" psql -X -v ON_ERROR_STOP=1 -U supabase_admin -d postgres -Atc "$call" >"$tmp/2" & wait
[[ "$(grep -h -c CREATED "$tmp"/* | awk '{s+=$1} END{print s}')" == 1 ]]; [[ "$(grep -h -c RESUMED "$tmp"/* | awk '{s+=$1} END{print s}')" == 1 ]]; [[ "$(q "SELECT count(*) FROM public.document_evidence_confirmations WHERE client_entity_id='$c';")" == 1 ]]; [[ "$(q "SELECT count(*) FROM public.financial_document_revisions WHERE client_entity_id='$c';")" == 1 ]]
[[ "$(q "SELECT public.confirm_document_evidence_v1('$p','$c','$b','$u','$e','same',repeat('d',64),'invoice','{}')->>'outcome';")" == "IDEMPOTENCY_CONFLICT" ]]
[[ "$(q "SELECT public.confirm_document_evidence_v1('$p','$c','$b','$u','$e','changed',repeat('e',64),'invoice',jsonb_build_object('issuer_name','Vendor','document_number','INV-1','amount_minor','1100','currency_code','USD','minor_unit_exponent','2'))->>'outcome';")" == "CREATED" ]]
[[ "$(q "SELECT public.confirm_document_evidence_v1('$p','$c','$b','21000000-0000-0000-0000-000000000099','$e','foreign',repeat('f',64),'invoice','{}')->>'outcome';")" == "DESTINATION_REJECTED" ]]
[[ "$(q "SELECT count(*) FROM public.financial_document_revisions WHERE client_entity_id='$c';")" == 2 ]]
echo '021_DOCUMENT_EVIDENCE_CONCURRENCY_OK exact-race=created+resumed changed-confirmation=revision-2 cross-tenant=rejected'
